# espaços na memoria ram da maquina
# variar
# variáveis são dados únicos
# interpretador
# meio termo entre a linguagem humana e da máquina
# forçar a intenção = organização
# cidade = 'cidade' 
# cidade = 'são paulo'
# CIDADE = 'BH'
# Cidade = 'rj'

# nomear de forma semantica 
# semantica é dar o nome daquilo que ele é - boa prática 
  
# print(cidade)
# função de outpur, é uma saída de código, print()

# regras para criar variáveis:
# _ou letra #não pode começar por números 
# não pode conter caracteres especiais
# pode utilizar números, (só não pode começar pelo número)
# palavra composta snake_case

#linguagem de alto nível 
#
# aplicar o type, para chamar qual tipo de dado esta usando na variável
# CRTL : roda somente o que está selecionado 

# print('cadasro de usuários')
# nome = 'Denis Renan'
# idade = 37
# email = 'deniszanardo@gmail.com'
# peso = 80.50
# altura = 1.90
# endereco = 'rua maria marcolina, brás'
# graduacao = 'ads'
# casado = False

# print(nome)

# ENTRADA
# nome_2 = input('digite seu nome')
# print("nome2")

# numero = float(input('digite um numero: '))
# numero_2 = float(input('digite um numero: '))
# numero_3 = int(input('Digite o ano: '))

# soma = numero_1 + numero_2
# print(soma)


# print('IMC')


# peso =  float(input('Digite seu peso: '))
# altura  =  float(input('Digite sua altura: '))
# imc  =  peso/altura**2

# print('IMC', imc)

# print("sinais de calculo aritimetico")

# print(10+200) # soma
# print(10-200) # subtração 
# print(10*200) # multiplicação
# print(10/200) # divisão 
# print(10%200) # modulo 
# print(10**200) # potencia
# print(10//200) # divisão com duas barras

# variáveis - estruturas de dados 
# funcoes - print() input() float() int()
# sinais aritiméticos 

# sinais logicos

print(10 == 200) # comparar
print(10 > 200) # verifica se 1º número é maior  
print(10 < 200) # verifica se 1º número é menor
print(10 >=200) # maior ou igual
print(10 <= 200) # menor ou igual 
print(10 != 2) # diferente

