#Crie um programa que:
#Peça ao usuário dois números.

#Mostre:
# soma 
# subtração
# multiplicação 
# divisão.


#Verifique:
#Se os números são iguais.
#Se o primeiro número é maior que o segundo.
#Se pelo menos um dos números é maior que 10.

#atividade:

n1 = float(input("Digite um número: "))
n2 = float(input("Digite um número: "))

print(n1 + n2)
print(n1 - n2)
print(n1 * n2)
print(n1 // n2)

print(n1 == n2)
print(n1 > n2)
print(n1 >10)
print(n2 > 10)
